// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvp55J6CdFD7aSKe6Z5U-n8DkZaQrW9k',
    appId: '1:377747109649:web:10f9215dfb4dcee5ef5818',
    messagingSenderId: '377747109649',
    projectId: 'buildbot-46180',
    authDomain: 'buildbot-46180.firebaseapp.com',
    storageBucket: 'buildbot-46180.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsxX7XD2Bao9tQK3L9L4BzImLltPWbQeA',
    appId: '1:838595827606:ios:d033703100e9bff1c0efb7',
    messagingSenderId: '377747109649',
    projectId: 'buildbot-46180',
    storageBucket: 'buildbot-46180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbX4FHOeB6XPnQY1yjYxYdXRRIZ0kn-54',
    appId: '1:838595827606:ios:d033703100e9bff1c0efb7',
    messagingSenderId: '377747109649',
    projectId: 'buildbot-46180',
    storageBucket: 'buildbot-46180.appspot.com',
    iosClientId: '377747109649-hjmu7r5otie3ojvucu3flfpo3qev1a7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildbot',
  );
} 